# Generated by Django 6.0.2 on 2026-02-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('road_name', models.CharField(default='Unknown Road', max_length=100)),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Fatal', 'Fatal')], default='Minor', max_length=20)),
                ('description', models.TextField(default='Vehicle accident reported')),
                ('injuries', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('state', models.CharField(choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green')], default='Green', max_length=10)),
                ('cycle_time', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20, unique=True)),
                ('lat', models.FloatField(default=27.7172)),
                ('lng', models.FloatField(default=85.324)),
                ('speed', models.FloatField(default=0)),
                ('heading', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vehicle_id'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('speed', models.FloatField()),
                ('lane', models.CharField(max_length=10)),
                ('violation_type', models.CharField(choices=[('Overspeeding', 'Overspeeding'), ('Wrong Lane', 'Wrong Lane'), ('Red Light', 'Red Light'), ('No Helmet', 'No Helmet')], max_length=50)),
                ('video_clip', models.CharField(max_length=100)),
                ('fine_amount', models.IntegerField(default=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
